from __future__ import annotations

from pathlib import Path

import pandas as pd
from scipy import stats

try:
    from src.universe import ACTIVE_STOCK_TICKERS, MARKET_TICKER
except ModuleNotFoundError:
    from universe import ACTIVE_STOCK_TICKERS, MARKET_TICKER


EVENT_PANEL_PATH = Path("results/event_panel.csv")

EVENT_TYPE_ANALYSIS_PATH = Path("results/event_type_analysis.csv")
STRATEGY_CANDIDATES_PATH = Path("results/strategy_candidates.csv")

HORIZONS = [5, 10, 20]


def load_event_panel(path: Path = EVENT_PANEL_PATH) -> pd.DataFrame:
    """Load event panel generated by src/events.py."""
    if not path.exists():
        raise FileNotFoundError(
            f"Missing event panel: {path}. Run `python src/events.py` first."
        )

    events = pd.read_csv(path, parse_dates=["date"])

    required = {
        "ticker",
        "date",
        "event_direction",
        "future_5d_abnormal_return",
        "future_10d_abnormal_return",
        "future_20d_abnormal_return",
    }
    missing = required - set(events.columns)

    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    return events.sort_values(["date", "ticker"]).reset_index(drop=True)


def one_sample_t_stat(values: pd.Series) -> tuple[float, float]:
    """Return one-sample t-stat and p-value against zero."""
    clean = values.dropna()

    if len(clean) < 2:
        return float("nan"), float("nan")

    result = stats.ttest_1samp(clean, popmean=0.0)

    return float(result.statistic), float(result.pvalue)


def summarize_strategy(
    events: pd.DataFrame,
    strategy_name: str,
    horizon: int,
    return_col: str,
    direction_multiplier: float,
) -> dict[str, float | int | str]:
    """
    Summarize candidate strategy returns.

    direction_multiplier:
    +1 means trade in same direction as future abnormal return.
    -1 means reverse future abnormal return.
    """
    strategy_returns = direction_multiplier * events[return_col]
    t_stat, p_value = one_sample_t_stat(strategy_returns)

    return {
        "strategy": strategy_name,
        "horizon": f"{horizon}d",
        "n_events": len(events),
        "mean_return": strategy_returns.mean(),
        "avg_return_per_event_bps": strategy_returns.mean() * 10_000,
        "hit_rate": (strategy_returns > 0).mean(),
        "t_stat": t_stat,
        "p_value": p_value,
    }


def build_strategy_candidates(events: pd.DataFrame) -> pd.DataFrame:
    """Build candidate tables for drift and reversal strategies."""
    rows = []

    positive_events = events[events["event_direction"] == "positive"].copy()
    negative_events = events[events["event_direction"] == "negative"].copy()

    for horizon in HORIZONS:
        return_col = f"future_{horizon}d_abnormal_return"

        rows.append(
            summarize_strategy(
                events=positive_events,
                strategy_name="Positive Event Drift",
                horizon=horizon,
                return_col=return_col,
                direction_multiplier=1.0,
            )
        )

        rows.append(
            summarize_strategy(
                events=negative_events,
                strategy_name="Negative Event Reversal",
                horizon=horizon,
                return_col=return_col,
                direction_multiplier=1.0,
            )
        )

        rows.append(
            summarize_strategy(
                events=events,
                strategy_name="All Event Drift",
                horizon=horizon,
                return_col=return_col,
                direction_multiplier=1.0,
            )
        )

        rows.append(
            summarize_strategy(
                events=events,
                strategy_name="All Event Reversal",
                horizon=horizon,
                return_col=return_col,
                direction_multiplier=-1.0,
            )
        )

    candidates = pd.DataFrame(rows)
    candidates = candidates.sort_values(
        ["horizon", "mean_return"],
        ascending=[True, False],
    ).reset_index(drop=True)

    return candidates


def build_event_type_analysis(events: pd.DataFrame) -> pd.DataFrame:
    """Summarize average future abnormal returns by event direction."""
    rows = []

    for direction, direction_events in events.groupby("event_direction"):
        row: dict[str, float | int | str] = {
            "event_direction": direction,
            "n_events": len(direction_events),
            "n_tickers": direction_events["ticker"].nunique(),
        }

        for horizon in HORIZONS:
            return_col = f"future_{horizon}d_abnormal_return"
            values = direction_events[return_col]
            t_stat, p_value = one_sample_t_stat(values)

            row[f"{horizon}d_mean"] = values.mean()
            row[f"{horizon}d_avg_bps"] = values.mean() * 10_000
            row[f"{horizon}d_hit_rate"] = (values > 0).mean()
            row[f"{horizon}d_t_stat"] = t_stat
            row[f"{horizon}d_p_value"] = p_value

        rows.append(row)

    summary = pd.DataFrame(rows)
    return summary.sort_values("event_direction").reset_index(drop=True)


def print_candidate_summary(candidates: pd.DataFrame) -> None:
    """Print candidate strategy summary."""
    print(f"Saved event type analysis to: {EVENT_TYPE_ANALYSIS_PATH}")
    print(f"Saved strategy candidates to: {STRATEGY_CANDIDATES_PATH}")

    print()
    print("Strategy candidate table")
    print("------------------------")
    print(
        candidates[
            [
                "strategy",
                "horizon",
                "n_events",
                "mean_return",
                "avg_return_per_event_bps",
                "hit_rate",
                "t_stat",
                "p_value",
            ]
        ].to_string(index=False)
    )

    print()
    print("Best candidate by horizon")
    print("-------------------------")
    best_by_horizon = (
        candidates.sort_values(["horizon", "mean_return"], ascending=[True, False])
        .groupby("horizon")
        .head(1)
        .reset_index(drop=True)
    )
    print(
        best_by_horizon[
            [
                "horizon",
                "strategy",
                "n_events",
                "mean_return",
                "avg_return_per_event_bps",
                "hit_rate",
                "t_stat",
            ]
        ].to_string(index=False)
    )


def run_event_type_analysis() -> None:
    """Run event-type strategy candidate analysis."""
    events = load_event_panel()

    event_type_summary = build_event_type_analysis(events)
    candidates = build_strategy_candidates(events)

    EVENT_TYPE_ANALYSIS_PATH.parent.mkdir(parents=True, exist_ok=True)

    event_type_summary.to_csv(EVENT_TYPE_ANALYSIS_PATH, index=False)
    candidates.to_csv(STRATEGY_CANDIDATES_PATH, index=False)

    print_candidate_summary(candidates)


if __name__ == "__main__":
    run_event_type_analysis()