from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats


EVENT_PANEL_PATH = Path("results/event_panel.csv")

SIGNAL_PANEL_PATH = Path("results/signal_panel.csv")
SIGNAL_QUINTILE_PATH = Path("results/signal_quintiles.csv")
SIGNAL_IC_PATH = Path("results/signal_ic.csv")

FORWARD_RETURN_COLS = [
    "future_5d_abnormal_return",
    "future_10d_abnormal_return",
    "future_20d_abnormal_return",
]

SIGNAL_COLS = [
    "drift_score",
    "reversal_score",
    "confirmation_score",
]


def load_event_panel(path: Path = EVENT_PANEL_PATH) -> pd.DataFrame:
    """Load event panel generated by src/events.py."""
    if not path.exists():
        raise FileNotFoundError(
            f"Missing event panel: {path}. Run `python src/events.py` first."
        )

    events = pd.read_csv(path, parse_dates=["date"])

    required = {
        "ticker",
        "date",
        "event_direction",
        "event_strength",
        "volume_shock",
        "rolling_20d_abnormal_vol",
        "pre_20d_return",
        *FORWARD_RETURN_COLS,
    }

    missing = required - set(events.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    return events.sort_values(["date", "ticker"]).reset_index(drop=True)


def zscore(series: pd.Series) -> pd.Series:
    """Cross-sectional/simple z-score across all events."""
    std = series.std(ddof=0)

    if pd.isna(std) or std == 0:
        return pd.Series(0.0, index=series.index)

    return (series - series.mean()) / std


def add_signal_scores(events: pd.DataFrame) -> pd.DataFrame:
    """
    Add simple event-driven signal scores.

    These are intentionally simple first-pass scores. The goal is not to
    force a profitable strategy. The goal is to test whether event features
    have ranking power for future abnormal returns.

    Scores:
    - drift_score:
        signed event strength + volume confirmation - volatility penalty

    - reversal_score:
        absolute event strength + volatility penalty - volume confirmation

    - confirmation_score:
        volume confirmation + signed event strength
    """
    out = events.copy()

    out["signed_event_strength"] = out["event_strength"]
    out["abs_event_strength"] = out["event_strength"].abs()

    # Log transform volume shock to reduce the impact of extreme spikes.
    out["log_volume_shock"] = np.log1p(out["volume_shock"])

    # Volatility penalty: higher pre-event abnormal volatility is treated as noisier.
    out["volatility_penalty"] = out["rolling_20d_abnormal_vol"]

    out["z_signed_event_strength"] = zscore(out["signed_event_strength"])
    out["z_abs_event_strength"] = zscore(out["abs_event_strength"])
    out["z_log_volume_shock"] = zscore(out["log_volume_shock"])
    out["z_volatility_penalty"] = zscore(out["volatility_penalty"])
    out["z_pre_20d_return"] = zscore(out["pre_20d_return"])

    out["drift_score"] = (
        out["z_signed_event_strength"]
        + out["z_log_volume_shock"]
        - out["z_volatility_penalty"]
    )

    out["reversal_score"] = (
        out["z_abs_event_strength"]
        + out["z_volatility_penalty"]
        - out["z_log_volume_shock"]
    )

    out["confirmation_score"] = (
        out["z_signed_event_strength"]
        + out["z_log_volume_shock"]
    )

    return out


def safe_spearman_ic(x: pd.Series, y: pd.Series) -> tuple[float, float]:
    """
    Calculate Spearman rank correlation and p-value safely.
    """
    valid = pd.concat([x, y], axis=1).dropna()

    if len(valid) < 3:
        return np.nan, np.nan

    if valid.iloc[:, 0].nunique() < 2 or valid.iloc[:, 1].nunique() < 2:
        return np.nan, np.nan

    result = stats.spearmanr(valid.iloc[:, 0], valid.iloc[:, 1])
    return float(result.statistic), float(result.pvalue)


def build_signal_ic_table(signal_panel: pd.DataFrame) -> pd.DataFrame:
    """
    Build IC table for each signal against each forward abnormal return horizon.
    """
    rows = []

    for signal_col in SIGNAL_COLS:
        for return_col in FORWARD_RETURN_COLS:
            ic, p_value = safe_spearman_ic(signal_panel[signal_col], signal_panel[return_col])

            horizon = return_col.replace("future_", "").replace("_abnormal_return", "")

            rows.append(
                {
                    "signal": signal_col,
                    "horizon": horizon,
                    "spearman_ic": ic,
                    "p_value": p_value,
                    "n_events": signal_panel[[signal_col, return_col]].dropna().shape[0],
                }
            )

    return pd.DataFrame(rows)


def add_quintile_bucket(
    df: pd.DataFrame,
    signal_col: str,
    bucket_col: str,
    n_buckets: int = 5,
) -> pd.DataFrame:
    """
    Add signal quintile bucket.
    """
    out = df.copy()

    out[bucket_col] = pd.qcut(
        out[signal_col],
        q=n_buckets,
        labels=[f"Q{i}" for i in range(1, n_buckets + 1)],
        duplicates="drop",
    )

    return out


def summarize_signal_quintiles(signal_panel: pd.DataFrame) -> pd.DataFrame:
    """
    For each signal, summarize future abnormal returns by signal quintile.
    """
    rows = []

    for signal_col in SIGNAL_COLS:
        bucket_col = f"{signal_col}_quintile"
        bucketed = add_quintile_bucket(signal_panel, signal_col, bucket_col)

        for bucket, group_df in bucketed.groupby(bucket_col, observed=True):
            row = {
                "signal": signal_col,
                "quintile": str(bucket),
                "n_events": len(group_df),
                "avg_signal": group_df[signal_col].mean(),
                "avg_event_strength": group_df["event_strength"].mean(),
                "avg_volume_shock": group_df["volume_shock"].mean(),
            }

            for return_col in FORWARD_RETURN_COLS:
                horizon = return_col.replace("future_", "").replace("_abnormal_return", "")
                values = group_df[return_col].dropna()

                row[f"{horizon}_mean"] = values.mean()
                row[f"{horizon}_hit_rate"] = (values > 0).mean()

            rows.append(row)

    return pd.DataFrame(rows)


def build_q5_minus_q1_table(quintiles: pd.DataFrame) -> pd.DataFrame:
    """
    Compute Q5 minus Q1 spread for each signal and horizon.
    """
    rows = []

    for signal_col in SIGNAL_COLS:
        subset = quintiles[quintiles["signal"] == signal_col].copy()

        q1 = subset[subset["quintile"] == "Q1"]
        q5 = subset[subset["quintile"] == "Q5"]

        if q1.empty or q5.empty:
            continue

        row = {
            "signal": signal_col,
            "comparison": "Q5_minus_Q1",
        }

        for horizon in ["5d", "10d", "20d"]:
            row[f"{horizon}_mean_spread"] = (
                q5[f"{horizon}_mean"].iloc[0] - q1[f"{horizon}_mean"].iloc[0]
            )
            row[f"{horizon}_hit_rate_spread"] = (
                q5[f"{horizon}_hit_rate"].iloc[0] - q1[f"{horizon}_hit_rate"].iloc[0]
            )

        rows.append(row)

    return pd.DataFrame(rows)


def print_signal_ic(ic_table: pd.DataFrame) -> None:
    """Print IC table."""
    print()
    print("Signal IC table")
    print("---------------")
    print(ic_table.to_string(index=False))


def print_quintile_summary(quintiles: pd.DataFrame) -> None:
    """Print compact quintile summary focused on 20d returns."""
    print()
    print("Signal quintile summary, 20d abnormal returns")
    print("---------------------------------------------")
    print(
        quintiles[
            [
                "signal",
                "quintile",
                "n_events",
                "avg_signal",
                "20d_mean",
                "20d_hit_rate",
            ]
        ].to_string(index=False)
    )


def print_q5_minus_q1(spreads: pd.DataFrame) -> None:
    """Print Q5 minus Q1 spread table."""
    print()
    print("Q5 minus Q1 spreads")
    print("-------------------")
    print(spreads.to_string(index=False))


def run_signal_analysis() -> None:
    """Build signal scores, IC table, and quintile validation outputs."""
    events = load_event_panel()
    signal_panel = add_signal_scores(events)

    SIGNAL_PANEL_PATH.parent.mkdir(parents=True, exist_ok=True)

    signal_panel.to_csv(SIGNAL_PANEL_PATH, index=False)

    ic_table = build_signal_ic_table(signal_panel)
    ic_table.to_csv(SIGNAL_IC_PATH, index=False)

    quintiles = summarize_signal_quintiles(signal_panel)
    spreads = build_q5_minus_q1_table(quintiles)

    # Save one combined file with normal quintiles and Q5-Q1 rows separately.
    quintiles.to_csv(SIGNAL_QUINTILE_PATH, index=False)

    q5_q1_path = SIGNAL_QUINTILE_PATH.with_name("signal_q5_minus_q1.csv")
    spreads.to_csv(q5_q1_path, index=False)

    print(f"Saved signal panel to: {SIGNAL_PANEL_PATH}")
    print(f"Saved signal IC table to: {SIGNAL_IC_PATH}")
    print(f"Saved signal quintiles to: {SIGNAL_QUINTILE_PATH}")
    print(f"Saved Q5-Q1 spreads to: {q5_q1_path}")

    print_signal_ic(ic_table)
    print_quintile_summary(quintiles)
    print_q5_minus_q1(spreads)


if __name__ == "__main__":
    run_signal_analysis()